baseurl: "https://example.com"
languageCode: "en-us"
title: "Hugo Tania"
theme: "hugo-tania"
paginate: 6

params:
  titleEmoji: 'ðŸ˜Ž'
  socialOptions:
    github: https://github.com/WingLim
    email: email@example.com

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true